Fixes and Comments for the Audio module
samyeyo/LuaRT-documentation pull request #8
Opened 2024-01-13 17:06 UTC by endertitan100

- Deleted some files that were either duplicates or just test files
- Fixed a few spelling and grammar errors
- Added/Improved comments for the entire audio module

2024-01-14 18:13 UTC, samyeyo requested changes
Thank you for the changes.
But I don't agree with the proposition for a "Output" section, it doesn't provide useful informations for users and will need a lot of work to add this section to other help files

2024-01-14 23:18 UTC, endertitan100 commented
Sorry I forgot that I was messing around with that and I must have accidentally included that in the PR. I will try and fix this tomorrow

2024-01-15 20:04 UTC, endertitan100 commented
Should be fixed now

2024-01-15 20:54 UTC, samyeyo approved these changes

2024-01-15 20:55 UTC, merged